# Generated by Django 5.2.9 on 2026-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('radius_miles', models.IntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
